# .github/workflows/update-database.yml
name: Update Trading Database

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment variables
      run: |
        echo "GATE_API_KEY=${{ secrets.GATE_API_KEY }}" >> .env
        echo "GATE_API_SECRET=${{ secrets.GATE_API_SECRET }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=" >> .env
        echo "TELEGRAM_CHAT_ID=" >> .env
    
    - name: Update database
      run: python update_db.py
    
    - name: Commit and push if database changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trading_signals.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update database [skip ci]" && git push)